name: Simple Tool Deploy
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy to Test ToolShed
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Planemo
      run: |
        python -m pip install --upgrade pip
        pip install planemo
        
    - name: Create Planemo config
      run: |
        mkdir -p ~/.planemo
        cat > ~/.planemo.yml << EOF
        shed_username: millerjeremya
        sheds:
          testtoolshed:
            key: ${{ secrets.TESTTOOLSHED_API_KEY }}
        EOF
        
    - name: Lint tool
      run: |
        planemo lint beast2.xml
        
    - name: Deploy to Test ToolShed
      run: |
        planemo shed_upload --shed_target testtoolshed --name beast2_test
        
    - name: Show deployment status
      run: |
        echo "Tool deployed to: https://testtoolshed.g2.bx.psu.edu/view/millerjeremya/beast2"
